# Generated by Django 4.1.2 on 2022-12-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spin_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('hint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Value_choosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='prabhav', max_length=15)),
                ('value', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('datetime', models.CharField(max_length=50, null=True)),
                ('spin', models.BooleanField(default=False)),
                ('bet_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Value_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField()),
            ],
        ),
    ]
