# Generated by Django 4.1 on 2022-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_niickname_player_nickname_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
