# Generated by Django 4.1 on 2022-08-27 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_password1_remove_player_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
